FROM mcr.microsoft.com/dotnet/sdk:5.0
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash && apt-get install -y nodejs

COPY . ./
RUN dotnet build && \
    cd DotnetTemplate.Web && \
    npm install && \
    npm run build

WORKDIR /DotnetTemplate.Web

#ENTRYPOINT ["dotnet", "run"]
CMD dotnet run