name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: DotNet Buildd
      id: s0001
      run: dotnet build
      continue-on-error: true

    - name: Check on failures
      if: steps.s0001.outcome != 'success'
      run: echo "BOO" && exit 1

    - name: Dotnet test
      run: dotnet test

    - name: npm installation
      run: cd DotnetTemplate.Web && npm install

    - name: npm lint
      run: cd DotnetTemplate.Web && npm run lint

    - name: npm tests
      run: cd DotnetTemplate.Web && npm run test

    - name: TEST GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.14.0
      with:
        payload: "{\"text\":\"GitHub -> This is a test from Tarne\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
